---
title: "SDM Evaluations"
author: "Ben Weinstein"
date: "Friday, November 14, 2014"
output: html_document
---

```{r,warning=FALSE,message=FALSE}
#Load required libraries
library(ggplot2)
library(knitr)
library(plyr)
library(reshape2)
library(GGally)

opts_chunk$set(warning=FALSE,message=FALSE)
opts_chunk$set(cache=FALSE,fig.width=10,echo=TRUE)

#Set git path
gitpath<-"C:/Users/Ben/Documents/Pred_Obs/"
droppath<-"C:/Users/Ben/Dropbox/"

#Where are the niche models saved?
savefolder<-"C:/Users/Ben/Dropbox/Thesis/Pred_Realized/NicheModels/0.1/"

setwd(savefolder)
```

#Model Evaluation

```{r}
#Get the ROC model evaluation from file
model_eval<-list.files("C:/Users/Ben/Dropbox/Thesis/Pred_Realized/NicheModels/0.1/",full.name=TRUE,recursive=T,pattern="ModelRocEval.csv")
```

```{r}
model_eval<-rbind.fill(lapply(model_eval,read.csv))
colnames(model_eval)<-c("Model","Species","Stat")
#Plot
ggplot(model_eval, aes(x=Species,y=Model,fill=Stat)) + geom_tile() + scale_fill_gradient("ROC",limits=c(0,1),low="blue",high="red",na.value="white") + theme(axis.text.x=element_text(angle=-90))

ggsave("ModelROCEvaluations.jpeg",height=5,width=20,dpi=300)
```

Number of Species included based on Ensemble Niche model support.

```{r}
model_thresh<-sapply(seq(.5,.95,.05),function(x){
  table(model_eval$Stat > x,model_eval$Model)["TRUE",]
})

colnames(model_thresh)<-seq(.5,.95,.05)
model_thresh<-melt(model_thresh)

names(model_thresh)<-c("Model","ROC_Threshold","Number_of_Species")

ggplot(model_thresh,aes(x=ROC_Threshold,y=Number_of_Species,col=Model)) + geom_line(size=1.5) + geom_point() + geom_text(aes(label=Number_of_Species),vjust=4,size=5) + theme_bw()

ggsave("ModelThresholding.pdf",dpi=300,height=8,width=8)
```

#Comparison of evaluation statistics

```{r}
model_eval<-list.files("C:/Users/Ben/Dropbox/Thesis/Pred_Realized/NicheModels/0.1/",full.name=TRUE,recursive=T,pattern="ModelEval.csv")

#some legacy error here:
model_eval<-rbind.fill(lapply(model_eval,read.csv))
colnames(model_eval)<-c("Metric","Species","GBM","GLM","MAXENT")
model_e<-melt(model_eval,id.var=c("Metric","Species"))

#Plot with facets
p<-ggplot(model_e, aes(x=Species,y=variable,fill=value)) + geom_tile() + facet_wrap(~Metric) + theme(axis.text.x=element_text(angle=-90))
p + scale_fill_gradient("Score",limits=c(0,1),low="blue",high="red",na.value="white")+ theme_bw() + theme(axis.text.x = element_blank()) 
ggsave("ModelEvaluations.jpeg",height=6,width=11,dpi=300)

#How correlated are model scores
cast_mods<-dcast(model_e, Species~...)

#GBM correlations
ggpairs(cast_mods[,c(2,5,8)],lower=list(continuous="smooth",method="lm"))

svg("GBMmetriccor.svg",height=10,width=10)
ggpairs(cast_mods[,c(2,5,8)],lower=list(continuous="smooth",method="lm"))
dev.off()

#GLM correcation
ggpairs(na.omit(cast_mods[,c(3,6,9)]),na.rm=TRUE,lower=list(continuous="smooth",method="lm"))

svg("GLMmetriccor.svg",height=10,width=10)
ggpairs(na.omit(cast_mods[,c(3,6,9)]),na.rm=TRUE,lower=list(continuous="smooth",method="lm"))
dev.off()

#Maxent Correlation
ggpairs(cast_mods[,c(4,7,10)],lower=list(continuous="smooth",method="lm"))

svg("Maxentmetriccor.svg",height=10,width=10)
ggpairs(cast_mods[,c(4,7,10)],lower=list(continuous="smooth",method="lm"))
dev.off()

ggplot(model_e,aes(x=variable,y=value)) + facet_wrap(~Metric) + geom_boxplot()+ geom_smooth(method="lm") + theme_bw() + labs(y="Score",x="Model")
```

#Variable importance
```{r}
varI<-list.files("C:/Users/Ben/Dropbox/Thesis/Pred_Realized/NicheModels/0.1/",full.name=TRUE,recursive=T,pattern="VarImportance.csv")
varI<-rbind.fill(lapply(varI,read.csv))
varI<-varI[,-1]

#Melt variable for plotting
mvar<-melt(varI)
colnames(mvar)<-c("Bioclim","Species","Model","value")

#Plot variable importance across all models
ggplot(mvar, aes(x=Species,y=Bioclim,fill=value)) + geom_tile() + scale_fill_gradient(limits=c(0,1),low="blue",high="red",na.value="white") + theme(axis.text.x=element_text(angle=-90)) + facet_grid(Model ~ .) + ggtitle("Variable Importance")

ggsave("VariableImportance.jpeg",height=5,width=15,dpi=300)
```
